<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>VSEvolutionHelper</AssemblyName>
    <RootNamespace>VSItemTooltips</RootNamespace>
    <RuntimeFlavor>IL2CPP</RuntimeFlavor>
    <OutputPath>bin/$(Configuration)/il2cpp/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BepInExPath Condition="'$(BepInExPath)' == ''">$(VSEVOLUTIONHELPER_BEPINEX_PATH)</BepInExPath>
    <GameReferencePath>$(MSBuildThisFileDirectory)lib/il2cpp</GameReferencePath>
  </PropertyGroup>
</Project>
